# =============
# Configuracion de la cuenta de correo
# -------------
 
# Protocolo
mail.protocol=smtp
#Host del correo
mail.smtp.host=
# Indica si requiere conectarse por tls
mail.smtp.starttls.enable=true
# Puerto
mail.smtp.port=
# Indica el emisor del correo
mail.smtp.mail.sender=
# Usuario
mail.smtp.user=
# Contraseña
mail.smtp.password=
# Indica si requiere autenticación
mail.smtp.auth=true
# Indica el nombre del emisor del correo
mail.from.name=Administrador FIRe
# Indica el tiempo de caducidad del restablecimiento de contrasena (milisegundos)
mail.password.expiration=1800000
# Destinatarios de la alarma
mail.recipients=
# Limite de notificaciones para enviar un correo resumen de alarmas.
mail.notify.limit=5
# Tiempo en el que si se acumula una cantidad de alarmas indicado en mail.notify.limit, se envia un correo resumen
mail.notify.delay.time=30
# Titulo del e-mail a enviar
mail.subject=Notificaci\u00F3n de alarma de FIRe
# Entorno en el que se encuentra desplegado el servicio (PRE, PRO, DESARROLLO, etc)
mail.environment=
