# =============
# Configuracion de la cuenta de correo
# -------------
 
# Protocolo
mail.protocol=smtp
#Host del correo
mail.smtp.host=
# Indica si requiere conectarse por tls
mail.smtp.starttls.enable=true
# Puerto
mail.smtp.port=
# Indica el emisor del correo
mail.smtp.mail.sender=
# Usuario
mail.smtp.user=
# Contraseña
mail.smtp.password=
# Indica si requiere autenticación
mail.smtp.auth=true
# Indica el nombre del emisor del correo
mail.from.name=Administrador FIRe


# =============
# Configuracion de la notificacion de alarmas
# -------------

# Cuentas de correo, separadas por comas (','), de los destinatarios de las alarmas en caso de no poder
# obtenerlos de BD
notification.recipients.backup=

# Numero de veces que una alarma de nivel CRITICA debe lanzarse dentro del periodo de tiempo indicado en
# "notification.period" antes de que se envie un correo notificandola
notification.critical.limit=1

# Numero de veces que una alarma de nivel ERROR debe lanzarse dentro del periodo de tiempo indicado en
# "notification.period" antes de que se envie un correo notificandola
notification.error.limit=3

# Numero de veces que una alarma de nivel ADVERTENCIA debe lanzarse dentro del periodo de tiempo indicado en
# "notification.period" antes de que se envie un correo notificandola
notification.warning.limit=10

# Numero de veces que una alarma de nivel INFORMATIVA debe lanzarse dentro del periodo de tiempo indicado en
# "notification.period" antes de que se envie un correo notificandola
notification.info.limit=20

# Tiempo en minutos dentro del cual deben haberse producido el numero de errores de un tipo concreto para que
# se envie una alarma
notification.period=30

# Tiempo de espera (en minutos) tras el envio de un correo de alarma hasta que se envia un correo resumen con
# las alarmas acumuladas.
notification.delay=30

# Entorno en el que se encuentra desplegado el servicio (PRE, PRO, DESARROLLO, etc)
deploy.environment=DESARROLLO
