-- ********************************************************
-- **************** Creacion de Tablas ********************
-- ********************************************************

CREATE TABLE "TB_APLICACIONES" (
  "ID" VARCHAR2(48) NOT NULL,
  "NOMBRE" VARCHAR2(45) NOT NULL,
  "RESPONSABLE" VARCHAR2(45) NOT NULL,
  "FECHA_ALTA" TIMESTAMP NOT NULL,
  "FK_CERTIFICADO" NUMBER NOT NULL,
  "HABILITADO" NUMBER(1,0) NOT NULL ENABLE, 
  constraint  "TB_APLICACIONES_PK" primary key ("ID")
); 


ALTER TABLE  "TB_APLICACIONES" modify
("FECHA_ALTA" TIMESTAMP default SYSDATE);


CREATE TABLE "TB_CERTIFICADOS" (
    "ID_CERTIFICADO"   NUMBER NOT NULL,
    "NOMBRE_CERT"      VARCHAR2(45) NOT NULL,
    "FEC_ALTA"         TIMESTAMP NOT NULL,
    "CERT_PRINCIPAL"   CLOB,
    "CERT_BACKUP"      CLOB,
    "HUELLA_PRINCIPAL" VARCHAR2(45),
    "HUELLA_BACKUP"    VARCHAR2(45),
    constraint  "TB_CERTIFICADOS_PK" primary key ("ID_CERTIFICADO")
);

CREATE SEQUENCE "TB_CERTIFICADOS_SEQ"; 


CREATE OR REPLACE TRIGGER "BI_TB_CERTIFICADOS"  
  before insert on "TB_CERTIFICADOS"              
  for each row 
begin  
  if :NEW."ID_CERTIFICADO" is null then
    select "TB_CERTIFICADOS_SEQ".nextval into :NEW."ID_CERTIFICADO" from dual;
  end if;
end;
/

ALTER TABLE  "TB_CERTIFICADOS" modify
("FEC_ALTA" TIMESTAMP default SYSDATE);

CREATE TABLE  "TB_USUARIOS" 
   ("ID_USUARIO" NUMBER NOT NULL ENABLE, 
	"NOMBRE_USUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(45) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(45) NOT NULL ENABLE, 
	"APELLIDOS" VARCHAR2(120) NOT NULL ENABLE, 
	"CORREO_ELEC" VARCHAR2(45), 
	"FEC_ALTA" TIMESTAMP (6) NOT NULL ENABLE, 
	"TELF_CONTACTO" VARCHAR2(45), 
	"ROL" VARCHAR2(45) DEFAULT ('admin') NOT NULL ,
	"USU_DEFECTO" NUMBER(1,0) NOT NULL ENABLE, 
	"CODIGO_RENOVACION" VARCHAR2(90) DEFAULT NULL,
	"FEC_RENOVACION" TIMESTAMP NOT NULL,
	"REST_CLAVE" NUMBER(1,0) NOT NULL ENABLE,	
	 CONSTRAINT "TB_USUARIOS_PK" PRIMARY KEY ("ID_USUARIO") ENABLE, 
	 CONSTRAINT "TB_USUARIOS_UK1" UNIQUE ("NOMBRE_USUARIO") ENABLE,
	 CONSTRAINT "TB_USUARIOS_UK2" UNIQUE ("CODIGO_RENOVACION") ENABLE
   ) ;
   
 CREATE TABLE "TB_ROLES" (
  "ID" NUMBER NOT NULL ENABLE,
  "NOMBRE_ROL" VARCHAR2(45) NOT NULL ENABLE,
  "PERMISOS"   VARCHAR2(45) NOT NULL ENABLE,
  CONSTRAINT "TB_ROLES_PK" PRIMARY KEY ("ID") ENABLE,
  CONSTRAINT "TB_ROLES_UK" UNIQUE ("NOMBRE_ROL") ENABLE
);

CREATE SEQUENCE "TB_USUARIOS_SEQ"; 

CREATE OR REPLACE TRIGGER  "BI_TB_USUARIOS" 
  before insert on "TB_USUARIOS"               
  for each row  
begin   
  if :NEW."ID_USUARIO" is null then 
    select "TB_USUARIOS_SEQ".nextval into :NEW."ID_USUARIO" from dual; 
  end if; 
end; 
/

ALTER TRIGGER  "BI_TB_USUARIOS" ENABLE;

ALTER TABLE  "TB_USUARIOS" modify
("USU_DEFECTO" NUMBER(1,0) default 0);

ALTER TABLE  "TB_USUARIOS" modify
("FEC_ALTA" TIMESTAMP default SYSDATE);

ALTER TABLE  "TB_USUARIOS" modify
("REST_CLAVE" NUMBER(1,0) default 0);


ALTER TABLE "TB_APLICACIONES" add constraint
"TB_APLICACIONES_FK" foreign key ("FK_CERTIFICADO") references "TB_CERTIFICADOS" ("ID_CERTIFICADO");
"TB_APLICACIONES_FK" foreign key ("FK_RESPONSABLE") references "TB_USUARIOS" ("ID_USUARIO");

ALTER TABLE "TB_USUARIOS" add constraint
"TB_USUARIOS_FK" foreign key ("FK_ROLE") references "TB_ROLES" ("id");



CREATE TABLE "TB_SERVIDORES_LOG" (
  "id_servidor" NUMBER NOT NULL ENABLE,
  "nombre" VARCHAR2(45) NOT NULL ENABLE, 
  "url_servicio_log" VARCHAR2(500) NOT NULL ENABLE, 
  "clave" VARCHAR2(45) NOT NULL ENABLE, 
  "verificar_ssl" NUMBER(1,0) NOT NULL ENABLE,
  CONSTRAINT "TB_SERVIDORES_LOG_PK" PRIMARY KEY ("id_servidor") ENABLE, 
  CONSTRAINT "TB_SERVIDORES_LOG_UK1" UNIQUE ("nombre") ENABLE,
  CONSTRAINT "TB_SERVIDORES_LOG_UK2" UNIQUE ("url_servicio_log") ENABLE
);


CREATE TABLE "TB_FIRMAS" (
  "id" NUMBER NOT NULL ENABLE,
  "fecha" TIMESTAMP (6) NOT NULL ENABLE,
  "aplicacion" VARCHAR2(45) NOT NULL ENABLE, 
  "formato" VARCHAR2(20) NOT NULL ENABLE, 
  "formato_mejorado" VARCHAR2(20) ENABLE,
  "algoritmo" VARCHAR2(20) NOT NULL ENABLE, 
  "proveedor" VARCHAR2(45) NOT NULL ENABLE, 
  "navegador" VARCHAR2(45) NOT NULL ENABLE, 
  "correcta" NUMBER(1,0) NOT NULL ENABLE,
  "total" NUMBER DEFAULT 0 NOT NULL ENABLE,
  CONSTRAINT "TB_FIRMAS_PK" PRIMARY KEY ("id") ENABLE
);


CREATE TABLE "TB_TRANSACCIONES" (
  "id" NUMBER NOT NULL ENABLE,
  "fecha" TIMESTAMP (6) NOT NULL ENABLE,
  "aplicacion" VARCHAR2(45) NOT NULL ENABLE,
  "operacion" VARCHAR2(10) NOT NULL ENABLE,
  "proveedor" VARCHAR2(45) NOT NULL ENABLE,
  "proveedor_forzado" NUMBER(1,0) NOT NULL ENABLE,
  "correcta" NUMBER(1,0) NOT NULL ENABLE,
  "tamanno" NUMBER DEFAULT 0 NOT NULL ENABLE,
  "total" NUMBER DEFAULT 0 NOT NULL ENABLE,
  CONSTRAINT "TB_TRANSACCIONES_PK" PRIMARY KEY ("id") ENABLE
);



