-- Script de migracion desde FIRe 2.2/2.3 a 2.4


-- Tabla para el guardado de las referencias a los servidores de log

CREATE TABLE "TB_SERVIDORES_LOG" (
  "ID_SERVIDOR" NUMBER NOT NULL,
  "NOMBRE" VARCHAR2(45) NOT NULL, 
  "URL_SERVICIO_LOG" VARCHAR2(500) NOT NULL, 
  "CLAVE" VARCHAR2(45) NOT NULL, 
  "VERIFICAR_SSL" NUMBER(1,0) NOT NULL,
  CONSTRAINT "TB_SERVIDORES_LOG_PK" PRIMARY KEY ("ID_SERVIDOR"), 
  CONSTRAINT "TB_SERVIDORES_LOG_UK1" UNIQUE ("NOMBRE"),
  CONSTRAINT "TB_SERVIDORES_LOG_UK2" UNIQUE ("URL_SERVICIO_LOG")
);

-- Tabla de las estadisticas de las firmas

CREATE TABLE "TB_FIRMAS" (
  "ID" NUMBER NOT NULL,
  "FECHA" TIMESTAMP (6) NOT NULL,
  "APLICACION" VARCHAR2(45) NOT NULL, 
  "FORMATO" VARCHAR2(20) NOT NULL, 
  "FORMATO_MEJORADO" VARCHAR2(20),
  "ALGORITMO" VARCHAR2(20) NOT NULL, 
  "PROVEEDOR" VARCHAR2(45) NOT NULL, 
  "NAVEGADOR" VARCHAR2(45) NOT NULL, 
  "CORRECTA" NUMBER(1,0) NOT NULL,
  "TOTAL" NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT "TB_FIRMAS_PK" PRIMARY KEY ("ID")
);

-- Tabla de estadisticas de las transacciones

CREATE TABLE "TB_TRANSACCIONES" (
  "ID" NUMBER NOT NULL,
  "FECHA" TIMESTAMP (6) NOT NULL,
  "APLICACION" VARCHAR2(45) NOT NULL,
  "OPERACION" VARCHAR2(10) NOT NULL,
  "PROVEEDOR" VARCHAR2(45) NOT NULL,
  "PROVEEDOR_FORZADO" NUMBER(1,0) NOT NULL,
  "CORRECTA" NUMBER(1,0) NOT NULL,
  "TAMANNO" NUMBER DEFAULT 0 NOT NULL,
  "TOTAL" NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT "TB_TRANSACCIONES_PK" PRIMARY KEY ("ID")
);

-- Tabla de roles

CREATE TABLE "TB_ROLES" (
  "ID" NUMBER NOT NULL,
  "NOMBRE_ROL" VARCHAR2(45) NOT NULL,
  "PERMISOS"   VARCHAR2(45),
  CONSTRAINT "TB_ROLES_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "TB_ROLES_UK" UNIQUE ("NOMBRE_ROL")
);

--   Insertamos los permisos de los roles
INSERT INTO TB_ROLES ("ID","NOMBRE_ROL","PERMISOS") 
VALUES(1,'admin','1,2');

INSERT INTO TB_ROLES ("ID","NOMBRE_ROL","PERMISOS") 
VALUES(2,'responsible','2');

INSERT INTO TB_ROLES ("ID","NOMBRE_ROL","PERMISOS") 
VALUES(3,'contact',NULL);


-- TABLA USUARIOS

ALTER TABLE "TB_USUARIOS" ADD "FK_ROL" NUMBER  default 1;
ALTER TABLE "TB_USUARIOS" ADD "CODIGO_RENOVACION" VARCHAR2(90) DEFAULT NULL;
ALTER TABLE "TB_USUARIOS" ADD "FEC_RENOVACION" TIMESTAMP DEFAULT NULL;
ALTER TABLE "TB_USUARIOS" ADD "REST_CLAVE" NUMBER(4,0) DEFAULT 0;

ALTER TABLE "TB_USUARIOS" DROP COLUMN "ROL";

ALTER TABLE  "TB_USUARIOS" MODIFY (clave VARCHAR2(45) NULL);    

ALTER TABLE "TB_USUARIOS"
ADD CONSTRAINT  "CODIGO_RENOVACION_UNQ" UNIQUE("CODIGO_RENOVACION");

-- Asignamos el rol administrador a todos los usuarios actuales, ya que hasta ahora todos los usuarios eran administradores
UPDATE "TB_USUARIOS" SET "FK_ROL" = 1;

ALTER TABLE "TB_USUARIOS" ADD CONSTRAINT
"TB_USUARIOS_FK" FOREIGN KEY ("FK_ROL") REFERENCES "TB_ROLES" ("ID");


-- Insertamos como usuarios a los responsables declarados en las aplicaciones
INSERT INTO "TB_USUARIOS" ("NOMBRE_USUARIO", "NOMBRE", "APELLIDOS", "CORREO_ELEC", "TELF_CONTACTO", "FEC_ALTA", "FK_ROL")
SELECT SUBSTR("ID", 1, 30), "RESPONSABLE", "RESPONSABLE", "RESP_CORREO", "RESP_TELEFONO", "FECHA_ALTA", 2
FROM "TB_APLICACIONES";


-- Tabla de relacion de responsables y aplicaciones

CREATE TABLE "TB_RESPONSABLE_DE_APLICACIONES" (
  "ID_RESPONSABLES" NUMBER NOT NULL,
  "ID_APLICACIONES" VARCHAR2(48) NOT NULL,
  PRIMARY KEY ("ID_RESPONSABLES","ID_APLICACIONES")
);


-- Agregamos la relacion entre las aplicaciones y los usuarios responsables de ellas
INSERT INTO "TB_RESPONSABLE_DE_APLICACIONES" ("ID_RESPONSABLES", "ID_APLICACIONES")
SELECT "ID_USUARIO", "NOMBRE_USUARIO"
FROM "TB_USUARIOS"
WHERE "FK_ROL" = 2;



-- TABLA APLICACIONES

-- Eliminamos los campos innecesarios de las aplicaciones
ALTER TABLE "TB_APLICACIONES"
DROP  (responsable,  resp_correo, resp_telefono);

-- Agregamos el campo de 'habilitado' dejando las aplicaciones habilitadas por defecto
ALTER TABLE "TB_APLICACIONES"
ADD HABILITADO NUMBER(1,0) DEFAULT 1;
 
