
# Configuracion para el envio de alarmas a GrayLog.
# El uso de este fichero y el envio de datos a GrayLog depende de que
# se haya activado este gestor de alarmas desde el fichero
# "fire_config.properties", a traves de la propiedad "alarms.notifier".

# =================================================================
# =============== NOTIFICACION DE ALARMAS A GRAYLOG ===============
# =================================================================

# Acceso habilitado
enabled=false

# IP de acceso al servicio de GrayLog
destination.host=127.0.0.1

# Puerto de acceso al servicio de GrayLog
destination.port=8080

# Parametros extra de configuracion. Pueden eliminarse o agregarse las
# propiedades que se deseen para configurar el stream de GrayLog. Se
# configuran utilizando el prefijo "field." (que se eliminara antes de
# enviarlo).
# Los modulos de FIRe siempre enviara un parametro "module" en el que se
# indicara el nombre del modulo (MODCENTRAL, ADMINISTRACION, etc)

# Entorno en el que se encuentra desplegado el servicio (PRE, PRO, DESAROLLO, etc)
field.entorno=LOCAL
