# =============
# Configuracion de la cuenta de correo
# -------------
 
# Protocolo
mail.protocol=smtp
#Host del correo
mail.smtp.host=
# Indica si requiere conectarse por tls
mail.smtp.starttls.enable=true
# Puerto
mail.smtp.port=
# Indica el emisor del correo
mail.smtp.mail.sender=pruebascorreoricoh@gmail.com
# Usuario
mail.smtp.user=
# Contraseña
mail.smtp.password=
# Indica si requiere autenticación
mail.smtp.auth=true
# Indica el nombre del emisor del correo
mail.from.name=Administrador FIRe
# Indica el tiempo de caducidad del restablecimiento de contrasena (milisegundos)
mail.password.expiration=1800000
# Destinatarios de la alarma
mail.recipients=jose.montero@ricoh.es
# Limite de notificaciones para enviar un correo
mail.notify.limits=5
