
# Configuracion para el envio de alarmas a GrayLog.
# El uso de este fichero y el envio de datos a GrayLog depende de que
# se haya activado este gestor de alarmas desde el fichero
# "fire_config.properties", a traves de la propiedad "alarms.notifier".

# =================================================================
# ============== NOTIFICACION DE ALARMAS POR CORREO ===============
# =================================================================
 
# Protocolo
mail.protocol=smtp
#Host del correo
mail.smtp.host=
# Indica si requiere conectarse por tls
mail.smtp.starttls.enable=true
# Puerto
mail.smtp.port=
# Indica el emisor del correo
mail.smtp.mail.sender=pruebascorreoricoh@gmail.com
# Usuario
mail.smtp.user=
# Contraseña
mail.smtp.password=
# Indica si requiere autenticación
mail.smtp.auth=true
# Indica el nombre del emisor del correo
mail.from.name=Administrador FIRe
# Indica el tiempo de caducidad del restablecimiento de contrasena (milisegundos)
mail.password.expiration=1800000
# Destinatarios de la alarma
mail.recipients=
# Limite de notificaciones de nivel CRITICAL para enviar un correo resumen de alarmas.
mail.critical.notify.limit=
# Limite de notificaciones de nivel ERROR para enviar un correo resumen de alarmas.
mail.error.notify.limit=
# Limite de notificaciones de nivel WARNING para enviar un correo resumen de alarmas.
mail.warning.notify.limit=
# Limite de notificaciones de nivel INFO para enviar un correo resumen de alarmas.
mail.info.notify.limit=
# Tiempo en el que si se acumula una cantidad de alarmas indicado en mail.XXX.notify.limit, se envia un correo resumen
mail.notify.delay.time=
# Titulo del e-mail a enviar
mail.subject=Notificaci\u00F3n de alarma de FIRe
# Entorno en el que se encuentra desplegado el servicio (PRE, PRO, DESARROLLO, etc)
mail.environment=
