
# Configuracion para el envio de alarmas a GrayLog.
# El uso de este fichero y el envio de datos a GrayLog depende de que
# se haya activado este gestor de alarmas desde el fichero
# "fire_config.properties", a traves de la propiedad "alarms.notifier".

# =================================================================
# ========= NOTIFICACION DE ALARMAS AL SISTEMA DE GESTION =========
# =================================================================

# Nombre del nodo del servidor
hostname=

# Propiedad del sistema de la que obtener el nombre del nodo del servidor.
# Se ignora si se declara la propiedad "hostname"
hostname.variable=

# Identificador del sistema que notifica la alarma
system.id=

# Cadena en base a la cual se genera la clave de comunicacion con el sistema
system.key=

# URL del servicio al que notificar las alarmas
service.url=

# Parametros extra de configuracion. Pueden eliminarse o agregarse las
# propiedades que se deseen para configurar el stream de GrayLog. Se
# configuran utilizando el prefijo "field." (que se eliminara antes de
# enviarlo).
# Los modulos de FIRe siempre enviara un parametro "module" en el que se
# indicara el nombre del modulo (MODCENTRAL, ADMINISTRACION, etc)

# Entorno en el que se encuentra desplegado el servicio (PRE, PRO, DES, etc)
field.entorno=DES