-- ********************************************************
-- **************** Insercion datos ********************
-- ********************************************************

--   Insertamos los permisos de los roles
INSERT INTO TB_ROLES ("ID","NOMBRE_ROL","PERMISOS") 
VALUES(1,'admin','1,2');

INSERT INTO TB_ROLES ("ID","NOMBRE_ROL","PERMISOS") 
VALUES(2,'responsible','2');

INSERT INTO TB_ROLES ("ID","NOMBRE_ROL","PERMISOS") 
VALUES(3,'contact',NULL);

-- USUARIO POR DEFECTO --------
INSERT INTO TB_USUARIOS ("NOMBRE_USUARIO", "CLAVE", "NOMBRE", "APELLIDOS", "USU_DEFECTO", "FK_ROL", "DNI")
VALUES('admin','$2y$12$JfP4bTV0i29Mnb3XBPOQl.L8JdbTrpn4fQljv8EEJKIp6NRZLB5TC','default name','default surnames',1,1,'X0000000T');


-- Insertar valores en la tabla TIPO_PLANIFICADOR
INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (0, 'TIPO_PLANIFICADOR00');

INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (1, 'TIPO_PLANIFICADOR01');

INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (2, 'TIPO_PLANIFICADOR02');

-- Insertar valores en la tabla PLANIFICADOR
INSERT INTO TB_PLANIFICADOR (ID_PLANIFICADOR, HORA_PERIODO, MINUTO_PERIODO, SEGUNDO_PERIODO, DIA_INICIO, ID_TIPO_PLANIFICADOR) 
VALUES (1, 24, 0, 0, TO_TIMESTAMP('01/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1);

-- Insertar valores en la tabla PROGRAMADOR
INSERT INTO TB_PROGRAMADOR (ID_PROGRAMADOR, NOMBRE_TOKEN, NOMBRE_CLASE, ESTA_ACTIVO, NUM_HILOS, NUM_PROCESOS, PERIODO_EXPIRADO, TIEMPO_REASIGNACION, TIEMPO_REACTIVACION, TIEMPO_COMPROBACION, ID_PLANIFICADOR, NOMBRE_PROGRAMADOR) 
VALUES (1, 'PROGRAMADOR01', 'es.gob.fire.control.tasks.TaskVerifyCertExpired', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 1, 'TaskVerifyCertExpired');

COMMIT;
