-- Script de migracion desde FIRe 2.4 a 2.5


-- TABLA de usuarios

-- Agregamos un campo DNI con un valor preestablecido para las entradas existentes
ALTER TABLE "TB_USUARIOS" ADD DNI VARCHAR(9) NULL;
UPDATE "TB_USUARIOS" SET DNI = 'X0000000T' WHERE id_usuario = 1;
-- Agregamos un campo FEC_ULTIMO_ACCESO con un valor preestablecido para las entradas existentes
ALTER TABLE "TB_USUARIOS" ADD FEC_ULTIMO_ACCESO TIMESTAMP DEFAULT SYSDATE;

-- TABLA de certificados

ALTER TABLE "TB_CERTIFICADOS" RENAME COLUMN CERT_PRINCIPAL TO CERTIFICADO;
ALTER TABLE "TB_CERTIFICADOS" RENAME COLUMN HUELLA_PRINCIPAL TO HUELLA;
ALTER TABLE "TB_CERTIFICADOS" DROP COLUMN CERT_BACKUP;
ALTER TABLE "TB_CERTIFICADOS" DROP COLUMN HUELLA_BACKUP;

-- Tabla de relacion de certificados y aplicaciones

CREATE TABLE "TB_CERTIFICADOS_DE_APLICACION" (
  "ID_CERTIFICADOS" NUMBER NOT NULL,
  "ID_APLICACIONES" VARCHAR2(48) NOT NULL,
  CONSTRAINT "TB_CERT_APP_PK" PRIMARY KEY ("ID_CERTIFICADOS","ID_APLICACIONES")
);

-- TABLA aplicaciones

ALTER TABLE "TB_APLICACIONES" DROP COLUMN FK_CERTIFICADO;