-- Script de migracion desde FIRe 2.4 a 2.5

-- TABLA DE USUARIOS

-- Agregamos los campos necesarios
ALTER TABLE `tb_usuarios`
ADD `dni` VARCHAR(9) NULL,
ADD `fec_ultimo_acceso` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE `tb_usuarios`
SET `dni` = 'X0000000T';


-- TABLA DE CERTIFICADOS

ALTER TABLE `tb_certificados` CHANGE COLUMN `cert_principal` `certificado` varchar(5000);
ALTER TABLE `tb_certificados` CHANGE COLUMN `huella_principal` `huella` varchar(45);
ALTER TABLE `tb_certificados` DROP COLUMN `cert_backup`;
ALTER TABLE `tb_certificados` DROP COLUMN `huella_backup`;
ALTER TABLE `tb_certificados` ADD `fec_caducidad` datetime NULL;
ALTER TABLE `tb_certificados` ADD `fec_inicio` datetime NULL;
ALTER TABLE `tb_certificados` ADD `subject` varchar(4000) NULL;

-- TABLA DE CERTIFICADOS DE APLICACION

CREATE TABLE `tb_certificados_de_aplicacion` (
  `id_certificados` int(11) NOT NULL,
  `id_aplicaciones` varchar(48) NOT NULL,
  PRIMARY KEY (`id_certificados`,`id_aplicaciones`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

-- TABLA DE APLICACIONES

ALTER TABLE `tb_aplicaciones` DROP COLUMN `fk_certificado`;

-- Tabla TIPO_PLANIFICADOR
CREATE TABLE TB_TIPO_PLANIFICADOR (
  ID_TIPO_PLANIFICADOR BIGINT NOT NULL,
  NOMBRE_TOKEN VARCHAR(30) NOT NULL,
  CONSTRAINT PK_ID_TIPO_PLANIFICADOR PRIMARY KEY (ID_TIPO_PLANIFICADOR)
);

-- Tabla PLANIFICADOR
CREATE TABLE TB_PLANIFICADOR (
  ID_PLANIFICADOR BIGINT NOT NULL,
  HORA_PERIODO INT(3),
  MINUTO_PERIODO INT(3),
  SEGUNDO_PERIODO INT(3),
  DIA_INICIO DATETIME,
  ID_TIPO_PLANIFICADOR BIGINT NOT NULL,
  AVISO_ANTICIPADO INT(3),
  CONSTRAINT PK_ID_PLANIFICADOR PRIMARY KEY (ID_PLANIFICADOR),
  CONSTRAINT FK_TIPO_PLANIFICADOR FOREIGN KEY (ID_TIPO_PLANIFICADOR) 
    REFERENCES TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR)
);

-- Tabla PROGRAMADOR
CREATE TABLE TB_PROGRAMADOR (
  ID_PROGRAMADOR BIGINT NOT NULL,
  NOMBRE_TOKEN VARCHAR(30) NOT NULL,
  NOMBRE_CLASE VARCHAR(255) NOT NULL,
  ESTA_ACTIVO CHAR(1) NOT NULL,
  NUM_HILOS BIGINT,
  NUM_PROCESOS BIGINT,
  PERIODO_EXPIRADO BIGINT,
  TIEMPO_REASIGNACION BIGINT,
  TIEMPO_REACTIVACION BIGINT,
  TIEMPO_COMPROBACION BIGINT,
  ID_PLANIFICADOR BIGINT NOT NULL,
  NOMBRE_PROGRAMADOR VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ID_PROGRAMADOR PRIMARY KEY (ID_PROGRAMADOR),
  CONSTRAINT UNICO_NOMBRE_PROGRAMADOR UNIQUE (NOMBRE_PROGRAMADOR),
  CONSTRAINT FK_PLANIFICADOR FOREIGN KEY (ID_PLANIFICADOR) 
    REFERENCES TB_PLANIFICADOR (ID_PLANIFICADOR)
);

-- Crear secuencia simulada con AUTO_INCREMENT
ALTER TABLE TB_PLANIFICADOR MODIFY ID_PLANIFICADOR BIGINT AUTO_INCREMENT;

-- Insertar valores en la tabla TIPO_PLANIFICADOR
INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (0, 'TIPO_PLANIFICADOR00');

INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (1, 'TIPO_PLANIFICADOR01');

INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (2, 'TIPO_PLANIFICADOR02');

-- Insertar valores en la tabla PLANIFICADOR
INSERT INTO TB_PLANIFICADOR (ID_PLANIFICADOR, HORA_PERIODO, MINUTO_PERIODO, SEGUNDO_PERIODO, DIA_INICIO, ID_TIPO_PLANIFICADOR) 
VALUES (1, 24, 0, 0, STR_TO_DATE('01/01/2012 00:00:00', '%m/%d/%Y %H:%i:%s'), 1);

-- Insertar valores en la tabla PROGRAMADOR
INSERT INTO TB_PROGRAMADOR (ID_PROGRAMADOR, NOMBRE_TOKEN, NOMBRE_CLASE, ESTA_ACTIVO, NUM_HILOS, NUM_PROCESOS, PERIODO_EXPIRADO, TIEMPO_REASIGNACION, TIEMPO_REACTIVACION, TIEMPO_COMPROBACION, ID_PLANIFICADOR, NOMBRE_PROGRAMADOR) 
VALUES (1, 'PROGRAMADOR01', 'es.gob.fire.control.tasks.TaskVerifyCertExpired', 'N', NULL, NULL, NULL, NULL, NULL, NULL, 1, 'TaskVerifyCertExpired');
