-- Script de migracion desde FIRe 2.4 a 2.5

-- TABLA DE USUARIOS

-- Agregamos los campos necesarios
ALTER TABLE `tb_usuarios`
ADD `dni` VARCHAR(9) NULL,
ADD `fec_ultimo_acceso` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE `tb_usuarios`
SET `dni` = 'X0000000T';

ALTER TABLE `tb_usuarios` DROP COLUMN IF EXISTS `nombre_usuario`;
ALTER TABLE `tb_usuarios` DROP COLUMN IF EXISTS `clave`;


-- TABLA DE CERTIFICADOS
ALTER TABLE `tb_certificados` CHANGE COLUMN `cert_principal` `certificado` varchar(5000);
ALTER TABLE `tb_certificados` CHANGE COLUMN `huella_principal` `huella` varchar(45);
ALTER TABLE `tb_certificados` DROP COLUMN `cert_backup`;
ALTER TABLE `tb_certificados` DROP COLUMN `huella_backup`;
ALTER TABLE `tb_certificados` ADD `fec_caducidad` datetime NULL;
ALTER TABLE `tb_certificados` ADD `fec_inicio` datetime NULL;
ALTER TABLE `tb_certificados` ADD `subject` varchar(4000) NULL;
ALTER TABLE `tb_certificados` ADD `fecha_ultima_comunicacion` datetime NULL;

-- TABLA DE CERTIFICADOS DE APLICACION

CREATE TABLE `tb_certificados_de_aplicacion` (
  `id_certificados` int(11) NOT NULL,
  `id_aplicaciones` varchar(48) NOT NULL,
  PRIMARY KEY (`id_certificados`,`id_aplicaciones`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

-- TABLA DE APLICACIONES

ALTER TABLE `tb_aplicaciones` DROP COLUMN `fk_certificado`;
ALTER TABLE `tb_aplicaciones` ADD `organization` VARCHAR(255) NULL;
ALTER TABLE `tb_aplicaciones` ADD `dir3_code` VARCHAR(50) NULL;
ALTER TABLE `tb_aplicaciones` ADD `proveedor_personalizado` char(1) DEFAULT 'N' NOT NULL;
ALTER TABLE `tb_aplicaciones` ADD `tamano_personalizado` char(1) DEFAULT 'N' NOT NULL;
ALTER TABLE `tb_aplicaciones` ADD `tamano_maximo_documento` bigint;
ALTER TABLE `tb_aplicaciones` ADD `tamano_maximo_peticion` bigint;
ALTER TABLE `tb_aplicaciones` ADD `cantidad_maxima_documentos` bigint;


-- Tabla TIPO_PLANIFICADOR
CREATE TABLE TB_TIPO_PLANIFICADOR (
  ID_TIPO_PLANIFICADOR BIGINT NOT NULL,
  NOMBRE_TOKEN VARCHAR(30) NOT NULL,
  CONSTRAINT PK_ID_TIPO_PLANIFICADOR PRIMARY KEY (ID_TIPO_PLANIFICADOR)
);

-- Tabla PLANIFICADOR
CREATE TABLE TB_PLANIFICADOR (
  ID_PLANIFICADOR BIGINT NOT NULL,
  HORA_PERIODO INT(3),
  MINUTO_PERIODO INT(3),
  SEGUNDO_PERIODO INT(3),
  DIA_INICIO DATETIME,
  ID_TIPO_PLANIFICADOR BIGINT NOT NULL,
  AVISO_ANTICIPADO INT(3),
  CONSTRAINT PK_ID_PLANIFICADOR PRIMARY KEY (ID_PLANIFICADOR),
  CONSTRAINT FK_TIPO_PLANIFICADOR FOREIGN KEY (ID_TIPO_PLANIFICADOR) 
    REFERENCES TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR)
);

-- Tabla PROGRAMADOR
CREATE TABLE TB_PROGRAMADOR (
  ID_PROGRAMADOR BIGINT NOT NULL AUTO_INCREMENT,
  NOMBRE_TOKEN VARCHAR(30) NOT NULL,
  NOMBRE_CLASE VARCHAR(255) NOT NULL,
  ESTA_ACTIVO CHAR(1) NOT NULL,
  NUM_HILOS BIGINT,
  NUM_PROCESOS BIGINT,
  PERIODO_EXPIRADO BIGINT,
  TIEMPO_REASIGNACION BIGINT,
  TIEMPO_REACTIVACION BIGINT,
  TIEMPO_COMPROBACION BIGINT,
  DIAS_PREAVISO BIGINT,
  PERIODO_COMUNICACION BIGINT,
  ID_PLANIFICADOR BIGINT NOT NULL,
  NOMBRE_PROGRAMADOR VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ID_PROGRAMADOR PRIMARY KEY (ID_PROGRAMADOR),
  CONSTRAINT UNICO_NOMBRE_PROGRAMADOR UNIQUE (NOMBRE_PROGRAMADOR),
  CONSTRAINT FK_PLANIFICADOR FOREIGN KEY (ID_PLANIFICADOR) 
    REFERENCES TB_PLANIFICADOR (ID_PLANIFICADOR)
);

-- Tabla CONTROL DE ACCESO
CREATE TABLE TB_CONTROL_ACCESO (
    ID_CONTROL_ACCESO BIGINT NOT NULL AUTO_INCREMENT,
    IP VARCHAR(45) NOT NULL,
    FECHA_INICIO_ACCESO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_CONTROL_ACCESO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla TB_PROVEEDORES
CREATE TABLE `tb_proveedores` (
  `id_proveedor` bigint NOT NULL,
  `nombre` varchar(50) NOT NULL,
  `obligatorio` char(1) NOT NULL,
  `habilitado` char(1) NOT NULL,
  `orden` tinyint(4) NOT NULL,
  
  PRIMARY KEY (`id_proveedor`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

-- Tabla TB_PROVEEDORES_APLICACION
CREATE TABLE `tb_proveedores_aplicacion` (
  `id_proveedor` bigint NOT NULL,
  `id_aplicacion` varchar(48) NOT NULL,
  `obligatorio` char(1) NOT NULL,
  `habilitado` char(1) NOT NULL,
  `orden` tinyint(4) NOT NULL,
  
  PRIMARY KEY (`id_aplicacion`, `id_proveedor`),
  CONSTRAINT `fk_aplicacion` FOREIGN KEY (`id_aplicacion`) REFERENCES `tb_aplicaciones` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proveedor` FOREIGN KEY (`id_proveedor`) REFERENCES `tb_proveedores` (`id_proveedor`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

-- Tabla TB_PROPIEDADES
CREATE TABLE `tb_propiedades` (
  `clave` varchar(255) NOT NULL,
  `valor_texto` varchar(4000),
  `valor_numerico` decimal(19,4),
  `valor_fecha` datetime,
  `tipo` varchar(20) NOT NULL,
  
  PRIMARY KEY (`clave`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

-- Insertar valores en la tabla TIPO_PLANIFICADOR
INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (0, 'TIPO_PLANIFICADOR00');

INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (1, 'TIPO_PLANIFICADOR01');

INSERT INTO TB_TIPO_PLANIFICADOR (ID_TIPO_PLANIFICADOR, NOMBRE_TOKEN) 
VALUES (2, 'TIPO_PLANIFICADOR02');

-- Insertar valores en la tabla PLANIFICADOR
INSERT INTO TB_PLANIFICADOR (ID_PLANIFICADOR, HORA_PERIODO, MINUTO_PERIODO, SEGUNDO_PERIODO, DIA_INICIO, ID_TIPO_PLANIFICADOR) 
VALUES (1, 24, 0, 0, STR_TO_DATE('01/01/2012 00:00:00', '%m/%d/%Y %H:%i:%s'), 1);

-- Insertar valores en la tabla PROGRAMADOR
INSERT INTO TB_PROGRAMADOR (ID_PROGRAMADOR, NOMBRE_TOKEN, NOMBRE_CLASE, ESTA_ACTIVO, NUM_HILOS, NUM_PROCESOS, PERIODO_EXPIRADO, TIEMPO_REASIGNACION, TIEMPO_REACTIVACION, TIEMPO_COMPROBACION, DIAS_PREAVISO, PERIODO_COMUNICACION, ID_PLANIFICADOR, NOMBRE_PROGRAMADOR) 
VALUES (1, 'PROGRAMADOR01', 'es.gob.fire.control.tasks.TaskVerifyCertExpired', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'TaskVerifyCertExpired');
