
# Configuracion de la conexion con la plataforma de actualizacion y validacion
# de firmas. Las propiedades aqui presentadas son las necesarias para
# configurar la conexion con la Plataforma @firma. Si se configurase otra
# plataforma, seria necesario sustituir estas propiedades por las
# correspondientes a la misma. 


# Identificador de la aplicacion frente a la Plataforma @firma
#afirma.appId=minhap.seap.dtic.clavefirma
afirma.appId=map.nivel2soporte.monitorizacion

# Timeout de conexion (-1 sin timeout)
webservices.timeout=50000

# URL del servicio Afirma. Debe tener la barra ("/") final  
webservices.endpoint=http://des-afirma.redsara.es/afirmaws/services/

webservices.service.signupgrade=DSSAfirmaVerify
webservices.service.recoversignature=DSSAsyncRequestStatus

# Almacen de confianza para conexiones seguras
com.trustedstore.path					= C:/Users/carlos.gamuci/Documents/FIRe/Ficheros_Despliegue/Afirma_Desarrollo/trust-pafirma.jks
com.trustedstore.password 				= 1234
com.trustedstore.type					= JKS

# Metodo de autenticacion 
webservices.authorization.method		   = BinarySecurityToken

# Propiedades para el metodo BinarySecurityToken
webservices.authorization.ks.path		   = C:/Users/carlos.gamuci/Documents/FIRe/Ficheros_Despliegue/Afirma_Desarrollo/pafirma_keystore.jks
webservices.authorization.ks.type		   = JKS
webservices.authorization.ks.password	   = 123456
webservices.authorization.ks.cert.alias    = alias
webservices.authorization.ks.cert.password = 1234

# Propiedades para la validacion del certificado de firma de la respuesta. Si no se indican todas,
# se aceptará cualquier certificado de firma
webservices.authentication.ts.path=
webservices.authentication.ts.password=
webservices.authentication.ts.type=
webservices.authentication.cert.alias=