# properties
spring.thymeleaf.prefix=file:C:/Users/carlos.gamuci/Documents/FIRe/Repositorios-Github/fire/fire-admin-web/src/main/resources/templates/
#spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# debug/logging to help troubleshoot
#logging.level.org.thymeleaf=DEBUG
#logging.level.org.springframework.web.servlet.view=DEBUG
