# Identificador de proveedor utilizado por la aplicacion
sp.providername=21114293V_E04975701

# Nombre de la aplicacion
sp.applicationname=Demo-App

# URL de retorno de la aplicacion
sp.returnurl=https://appprueba:8443/fire-admin-web/ResponseClave

# Niveles:
#	- LOW: http://eidas.europa.eu/LoA/low
#	- SUBSTANCIAL: http://eidas.europa.eu/LoA/substantial
#	- HIGH: http://eidas.europa.eu/LoA/high
eidas.levelofassurance=http://eidas.europa.eu/LoA/substantial

# URL del servicio de Clave
service.url=https://se-pasarela.clave.gob.es/Proxy2/ServiceProvider

# Ruta del almacen de claves utilizado para la firma de las peticiones SAML
service.keystore.path=C:\\Users\\carlos.gamuci\\Documents\\FIRe\\Paquete de Integracion Java8 v3.0.0\\Paquete_Integracion_Java_Clave_8\\Config\\KeyStore.jks
# Tipo de almacen configurado en la propiedad "service.keystore.path" (JKS o PKCS12).
service.keystore.type=JKS
# Contrasena del almacen configurado en la propiedad "service.keystore.path".
service.keystore.password=local-demo
# Contrasena de de la clave con el alias de la propiedad "service.key.alias" que se utilizara para firmar las peticiones SAML
service.key.password=1234
# Alias del certificado del almacen configurado en la propiedad "service.keystore.path" que se utilizara para la firma de las peticiones SAML
service.key.alias=eidas certificado pruebas - 99999972c (ac fnmt usuarios)
